"""Pydantic schemas and request/response validation models."""

from typing import List, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request payload for chat endpoint."""

    message: str = Field(
        ...,
        min_length=1,
        description="The user's query or financial analysis prompt.",
        examples=["Summarize analyst recommendations and share the latest news for Nvidia"],
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session identifier for conversational continuity.",
        examples=["sess_12345"],
    )


class ChatResponse(BaseModel):
    """Response payload for chat endpoint."""

    response: str = Field(
        ...,
        description="The markdown formatted response generated by the financial multi-agent system.",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="The session identifier associated with this turn.",
    )
    status: str = Field(
        default="success",
        description="Status indicator ('success' or 'error').",
    )
    model_used: Optional[str] = Field(
        default=None,
        description="The LLM model and provider utilized for generation.",
    )


class ChatMessage(BaseModel):
    """Single chat turn message in episodic memory."""

    role: str = Field(..., description="Message author role ('user' or 'assistant').")
    content: str = Field(..., description="Message text content.")
    timestamp: Optional[float] = Field(default=None, description="Unix timestamp of message creation.")


class ChatHistoryResponse(BaseModel):
    """Response containing conversation history for a session."""

    session_id: str = Field(..., description="Session identifier.")
    messages: List[ChatMessage] = Field(default_factory=list, description="Ordered list of historical messages.")
    total_messages: int = Field(default=0, description="Total number of messages in session cache.")
    status: str = Field(default="success", description="Status indicator.")


class SessionClearResponse(BaseModel):
    """Response after clearing conversation memory."""

    session_id: str = Field(..., description="Session identifier.")
    cleared: bool = Field(..., description="Whether the session memory was successfully cleared.")
    message: str = Field(..., description="Status message description.")
    status: str = Field(default="success", description="Status indicator.")


class HealthResponse(BaseModel):
    """System health and readiness status."""

    status: str = Field(default="healthy", description="Service status.")
    version: str = Field(default="0.1.0", description="API version.")
    agent_ready: bool = Field(default=True, description="Whether the multi-agent system is initialized.")
    model_provider: str = Field(default="unknown", description="Active LLM provider.")
    model_id: str = Field(default="unknown", description="Active model identifier.")
    redis_connected: Optional[bool] = Field(default=None, description="Redis episodic memory connection status.")
    redis_status: Optional[str] = Field(default=None, description="Redis episodic memory status details.")


class ErrorResponse(BaseModel):
    """Error response model."""

    detail: str = Field(..., description="Error message description.")
    status: str = Field(default="error", description="Error status indicator.")
