"""Pydantic schemas and request/response validation models."""

from typing import Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request payload for chat endpoint."""

    message: str = Field(
        ...,
        min_length=1,
        description="The user's query or financial analysis prompt.",
        examples=["Summarize analyst recommendations and share the latest news for Nvidia"],
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session identifier for conversational continuity.",
        examples=["sess_12345"],
    )


class ChatResponse(BaseModel):
    """Response payload for chat endpoint."""

    response: str = Field(
        ...,
        description="The markdown formatted response generated by the financial multi-agent system.",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="The session identifier associated with this turn.",
    )
    status: str = Field(
        default="success",
        description="Status indicator ('success' or 'error').",
    )
    model_used: Optional[str] = Field(
        default=None,
        description="The LLM model and provider utilized for generation.",
    )


class HealthResponse(BaseModel):
    """System health and readiness status."""

    status: str = Field(default="healthy", description="Service status.")
    version: str = Field(default="0.1.0", description="API version.")
    agent_ready: bool = Field(default=True, description="Whether the multi-agent system is initialized.")
    model_provider: str = Field(default="unknown", description="Active LLM provider.")
    model_id: str = Field(default="unknown", description="Active model identifier.")


class ErrorResponse(BaseModel):
    """Error response model."""

    detail: str = Field(..., description="Error message description.")
    status: str = Field(default="error", description="Error status indicator.")
